### ISSUE TITLE
File type error

### ISSUE THREAD

**Issue by rcnava** [tasneemsmacros/ViaFuse#1]
I am very interested in your macro but I am working with images acquired on the thermofisher microscope. Are .lsm files specific to Ziess? I tried counting nulcei with the ViaFuse_V macro on a Dapi .TIF image but I get the file type error: 

Memory	*	1158MB of 3000MB (38%)

nImages()	*	1
getTitle()	*	"scan_Plate_TD_p00_0_A06f00d0.TIF"

---		---
Error:		Statement cannot begin with '<' in line 7:
	
		<<> ! DOCTYPE html > 

Is there a way to use this with my .TIF files or possibly convert to .lsm? I couldn't find much on the file type.

**Comment by tasneemsmacros** [comment]
Hi there, thanks for reaching out! .lsm files are not specific to Ziess. If you want to convert your .tif image to .lsm, here's a link that might be helpful: https://www.researchgate.net/post/How_to_convert_a_TIFF_file_into_LSM_format#:~:text=It%20is%20indeed%20possible%20to,meta%20data%20are%20still%20lost. 

The .tif image format should actually work as well with the macro! We ran the viafuse_v macro using a .tif image and didn't run into any errors. Could you please walk me through what you did step by step so that I may better assist you?
